---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_password: "manu@9148"

  tasks:
    - name: Login to docker registry
      shell: echo "{{ docker_registry_password }}" | docker login -u manu100 --password-stdin https://index.docker.io/v1/
    
    - name: pull image from docker hub
<<<<<<< HEAD
      shell: docker pull manu100/project:manu

    - name: docker run
      shell: docker run --init -d manu100/project:manu
=======
      shell: docker pull manu100/gowda:tagname

    - name: docker run
      shell: docker run --init -d manu100/gowda:tagname
>>>>>>> c2cf5518d9ae8247c4e452940a430abfffc31100
