on:
    push:
        branches: [master]
   

jobs:
    build:

        runs-on: index


      
       
        steps:
           
            - uses: actions/checkout@v4
           
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

                docker image build -t manu100/index:tagname .
                docker push manu100/index:tagname

                
            - name: run ansible playbook
              if: github.ref == 'refs/heads/master'
              env:
                password: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                  ansible-playbook ansible.yml -i manu.txt --extra-vars "password=$password"   

